In [27]:
dic_p = {}
class Soldier:
    def __init__(self, nombre, puntaje):
        self.nombre = nombre
        self.puntaje = puntaje
        dic_p[self.nombre] = self.puntaje 
    
    def dic_p2(self):
        print(self.nombre)
        dic_p[self.nombre] = self.puntaje 

In [28]:
Marcos = Soldier('marcos', 10)

In [30]:
print(dic_p)

{'marcos': 10}


In [22]:
Marcos.puntaje

10

In [23]:
Marcos.dic_p2()

marcos


In [29]:
print(dic_p)

{'marcos': 10}


In [1]:
class Crawler:
    def __init__(self, url, paginas=1, navegador = 'Chrome'):
        self.pagina_web = url
        self.npginas = paginas
        self.driver = navegador
    def acceder_pagina(self):
        print(f'Usando navegador {self.driver}')
        print(f'accedimos a la pagina {self.pagina_web}')
    def sacar_info(self):
        for pagina in range(self.npaginas):
            print(f'Usando navegador {pagina}')
class ScraperIronhack(Crawler):
    def __init__(self, user, password, url, paginas=1, navegador = 'Chrome'):
        self.user = user
        self.password = password
        super().__init__(url, paginas=1, navegador = 'Chrome')
    def iniciar_sesion(self):
        print(f'Iniciando sesion usuario {self.user}')
    def acceder_pagina(self):
        print(f'Usando navegador {self.driver}')
        print(f'Accedimos a la pagina {self.pagina_web}')
        print('Favor de iniciar sesion')
class ScraperInsta(Crawler):
    def __init__(self, user, password, url, paginas = 1, navegador = 'Chrome'):
        self.user = user
        self.password = password
        super().__init__(url, paginas, navegador)
    def iniciar_sesion(self):
        print(f'Iniciando sesion usuario {self.user}')
    def stalkear(self):
        print('Ya superala')

In [12]:

# Soldier


class Soldier:
    def __init__(self, health, strength):
        self.health = health
        self.strength = strength
    
    def attack(self):
        return self.strength
    
    def receiveDamage(self, receiveDamage):
        self.health = self.health - receiveDamage 
    pass

# Viking

class Viking(Soldier):
    def __init__(self, name, health, strength):
        self.name = name
        super().__init__(health, strength)
    
    def receiveDamage(self, receiveDamage):
        self.health = self.health - receiveDamage
        if self.health > 0:
            #print(f'{self.name} has received {receiveDamage} points of damage')
            return f'{self.name} has received {receiveDamage} points of damage'
        else:
            return f'{self.name} has died in act of combat'
    
    def battleCry(self):
        return 'Odin Owns You All!'
        
    pass

# Saxon


class Saxon(Soldier):
    def __init__(self, health, strength):
        super().__init__(health, strength)
        
    def receiveDamage(self, receiveDamage):
        self.health = self.health - receiveDamage
        if self.health > 0:
            #print(f'{self.name} has received {receiveDamage} points of damage')
            return f'A Saxon has received {receiveDamage} points of damage'
        else:
            return f'A Saxon has died in combat'
        
    pass

# War


class War:
    def __init__(self):
        self.vikingArmy = []
        self.saxonArmy = []
        
    def addViking(self, Viking):
        self.vikingArmy.append(Viking())
        
    def addSaxon(self, Saxon):
        self.saxonArmy.append(Saxon())
    
    #def vikingAttack(self):
    #    for item in self.saxonArmy:
    #        for item2 in self.vikingArmy:
    #            if item.receiveDamage == item2.strength:
    #                resul= item.receiveDamage - item2.strength
    #                self.saxonArmy.remove(item)
    #    return resul
    
    def vikingAttack(self):
        
        if Saxon.receiveDamage(Viking.strength) < 0:
            War.saxonArmy.remove(Saxon)
        return War.saxonArmy.remove(Saxon)
    
    def SaxonAttack(self):
        
        if Viking.receiveDamage(Saxon.strength) < 0:
            War.VikingArmy.remove(Viking.name)
        return War.VikingArmy.remove(Viking.name)
    
        def showStatus(self):
            if len(self.saxonArmy)==0:
                return "Vikings have won the war of the century!"
            if len(self.vikingArmy)==0:
                return "Saxons have fought for their lives and survive another day..."
            else:
                return "Vikings and Saxons are still in the thick of battle."
        
    pass


In [ ]:
def vikingAttack(self):
        resul=0
        for item in self.saxonArmy:
            for item2 in self.vikingArmy:
                if item.receiveDamage == item2.strength:
                    resul= item.receiveDamage - item2.strength
                    self.saxonArmy.remove(item)
        return resul
    
    def saxonAttack(self):
        resul=0
        for item in self.vikingArmy:
            for item2 in self.saxonArmy:
                if item.receiveDamage == item2.strength:
                    resul= item.receiveDamage - item2.strength
                    self.vikingArmy.remove(item)
        return resul
    

In [15]:
import numpy as np
g = np.empty([2,3,5])
print(g)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [1]:
n= [[1, 1, 1], 10]

In [35]:
n1=[1,1,1]

t=10
p=0

for p in range(t-3):
    x= len(n1)-3
    z=0
    print(t)
    for y in range(len(n1)):
        if y >= x:
            z=n1[y]+z
    n1.append(z)
    p=p+1
        
print(n1)

10
10
10
10
10
10
10
[1, 1, 1, 3, 5, 9, 17, 31, 57, 105]


In [33]:
for u in range (10):
    print(u)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#test.assert_equals(tribonacci([1, 1, 1], 10), [1, 1, 1, 3, 5, 9, 17, 31, 57, 105])

In [52]:
def tribonacci(signature, n):
    #n1=[1,1,1]
    n1=signature
    #t=10
    p=0
    if n==1:
        n1=[1]
        return n1
 
    
    if n==0:
        n1=[]
        return n1
    
    for p in range(n-3):
        x= len(n1)-3
        z=0
        #print(t)
        for y in range(len(n1)):
            if y >= x:
                z=n1[y]+z
        n1.append(z)
        p=p+1
    return n1




In [44]:
t=tribonacci([1, 1, 1], 10)
print(t)

[1, 1, 1, 3, 5, 9, 17, 31, 57, 105]


In [ ]:
#tribonacci([1, 1, 1], 1), [1])
#tribonacci([300, 200, 100], 0), [])

In [51]:
t=tribonacci([1, 1, 1], 1)
print(t)

[1]


In [53]:
t=tribonacci([1, 1, 1], 0)
print(t)

[]


In [56]:
def tribonacci(signature, n):
    #n1=[1,1,1]
    n1=signature
    #t=10
    p=0
    if n<= len(n1):
        #n1=[1]
        return n1[:n]
 
    for p in range(n-3):
        x= len(n1)-3
        z=0
        #print(t)
        for y in range(len(n1)):
            if y >= x:
                z=n1[y]+z
        n1.append(z)
        p=p+1
    return n1

In [58]:
t=tribonacci([1, 1, 1], 0)
print(t)

[]


In [61]:
def tribonacci(signature,n):
    while len(signature) < n:
        signature.append(sum(signature[-3:]))
    
    return signature[:n]


In [62]:
t=tribonacci([1, 1, 1], 0)
print(t)

[]


In [69]:
t = [1,2,3,4,5]
sum(t[1:3])

5

In [72]:
import numpy as np
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)


array([[4, 1],
       [2, 2]])

In [73]:
import numpy as np
a = [[1, 1], [1, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[6, 3],
       [6, 3]])

In [76]:
import numpy as np
a = [2, 2]
b = [4, 1]
np.dot(a, b)

10

In [77]:
!pip install PyMySQL

     |████████████████████████████████| 43 kB 551 kB/s eta 0:00:01


In [78]:
!pip install SQLAlchemy

In [240]:
from sqlalchemy import create_engine, text
import pandas as pd

In [241]:
#url_local = "mysql+pymysql://root:davidob18@Ironhack:3306/sakila"  127.0.0.1
#url_local = "mysql+pymysql://root:davidob18@localhost:3306/sakila"
url_local = "mysql+pymysql://root:davidob18@127.0.0.1:3306/sakila"
url_remoto = "mysql+pymysql://guest:relational@relational.fit.cvut.cz:3306/Airline"

In [242]:
engine = create_engine(url_local)
engine_remoto = create_engine(url_remoto)

In [243]:
df = pd.read_sql_query("SELECT * FROM film", engine)

In [244]:
df.head(5)

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id original_language_id  rental_duration  rental_rate  length  \
0            1                 None                6         0.99      86   
1            1                 None                3         4.99      48   
2            1                 None                7         2.99      50   
3            1                 None                5         2.99     117   
4            1                 None                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

          last_update  
0 2006-02-14 23:03:42  
1 2006-02-14 23:03:42  
2 2006-02-14 23:03:42  
3 2006-02-14 23:03:42  
4 2006-02-14 23:03:42

In [115]:
def Xbonacci(signature, n):
    res = signature[:n]
    for i in range(n - 3): res.append(sum(res[-2:]))
    return res

In [116]:
Xbonacci([0,0,0,0,1],10)

[0, 0, 0, 0, 1, 1, 2, 3, 5, 8, 13, 21]

In [117]:
#test.assert_equals(Xbonacci([0,1],10),[0,1,1,2,3,5,8,13,21,34])
test.assert_equals(Xbonacci([0,0,0,0,1],10),[0,0,0,0,1,1,2,4,8,16])

NameError: name 'test' is not defined

In [120]:
list_2 = [0,0,0,0,1]
n=10

print(len(list_2))

n2=n-len(list_2)

5


In [176]:
def Xbonacci(signature, n):
    n2=n-len(signature)
    z=len(signature)
    res = signature[:n]
    for i in range(n2): 
        res.append(sum(res[-z:]))
    return res

In [179]:
Xbonacci([0,0,0,0,1],10)

[0, 0, 0, 0, 1, 1, 2, 4, 8, 16]

In [178]:
Xbonacci([0,1],10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [172]:
#test.assert_equals(Xbonacci([0,1],10),[0,1,1,2,3,5,8,13,21,34])
test.assert_equals(Xbonacci([0,0,0,0,1],10),[0,0,0,0,1,1,2,4,8,16])
test.assert_equals(Xbonacci([1,0,0,0,0,0,1],10),[1,0,0,0,0,0,1,2,3,6])

NameError: name 'test' is not defined

In [177]:
Xbonacci([1,0,0,0,0,0,1],10)

[1, 0, 0, 0, 0, 0, 1, 2, 3, 6]

In [180]:
def Xbonacci(sig, n):
    if n <= 0:
        return []
    return [sig[0]] + Xbonacci(sig[1:] + [sum(sig)], n-1)

In [181]:
def Xbonacci(signature,n):
    if n <= 0:
        return []
    
    return signature[:1] + Xbonacci(signature[1:] + [sum(signature)], n-1)

In [208]:

def Xbonacci3(signature,n,k = 0):

    x=len(signature)   
    
    if x>=n:
        return signature[:n]
        
    signature_ext=signature+[sum(signature[k:])]
    k += 1
    return Xbonacci3(signature_ext,n, k)

In [209]:
Xbonacci3([0,1],10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [245]:
%time #TOMA LOS TITULOS QUE EMPIEZAN CON C
query = """SELECT * FROM film
WHERE title LIKE 'C%'"""

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 5.72 µs


In [246]:
df = pd.read_sql_query(text(query), engine)

In [247]:
df.head()

film_id              title  \
0      110        CABIN FLASH   
1      111    CADDYSHACK JEDI   
2      112  CALENDAR GUNFIGHT   
3      113   CALIFORNIA BIRDS   
4      114   CAMELOT VACATION   

                                         description  release_year  \
0  A Stunning Epistle of a Boat And a Man who mus...          2006   
1  A Awe-Inspiring Epistle of a Woman And a Madma...          2006   
2  A Thrilling Drama of a Frisbee And a Lumberjac...          2006   
3  A Thrilling Yarn of a Database Administrator A...          2006   
4  A Touching Character Study of a Woman And a Wa...          2006   

   language_id original_language_id  rental_duration  rental_rate  length  \
0            1                 None                4         0.99      53   
1            1                 None                3         0.99      52   
2            1                 None                4         4.99     120   
3            1                 None                4         4.99      75   
4            1                 None                3         0.99      61   

   replacement_cost rating                                   special_features  \
0             25.99  NC-17                        Commentaries,Deleted Scenes   
1             17.99  NC-17                        Commentaries,Deleted Scenes   
2             22.99  NC-17            Trailers,Commentaries,Behind the Scenes   
3             19.99  NC-17               Trailers,Commentaries,Deleted Scenes   
4             26.99  NC-17  Trailers,Commentaries,Deleted Scenes,Behind th...   

          last_update  
0 2006-02-14 23:03:42  
1 2006-02-14 23:03:42  
2 2006-02-14 23:03:42  
3 2006-02-14 23:03:42  
4 2006-02-14 23:03:42

In [249]:
%time #TOMA LOS TITULOS QUE EMPIEZAN CON C
query = """SELECT MIN(release_year), AVG(rental_rate) FROM film
WHERE title LIKE 'C%'
GROUP BY rating"""

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 7.15 µs


In [250]:
df = pd.read_sql_query(text(query), engine)

In [251]:
df.head()

MIN(release_year)  AVG(rental_rate)
0               2006          3.337826
1               2006          3.434444
2               2006          3.212222
3               2006          2.740000
4               2006          2.519412

In [252]:
query = """SELECT rating, MIN(release_year) AS first_year, AVG(rental_rate) AS mean_price FROM film
WHERE title LIKE 'C%'
GROUP BY rating
HAVING mean_price > 3"""

In [253]:
df = pd.read_sql_query(text(query), engine)

In [254]:
df.head()

rating  first_year  mean_price
0  NC-17        2006    3.337826
1      R        2006    3.434444
2      G        2006    3.212222

In [255]:
query = """SELECT rating, MIN(release_year) AS first_year, AVG(rental_rate) AS mean_price FROM film
GROUP BY rating
HAVING mean_price > 3 AND rating LIKE 'P%'"""

In [256]:
df = pd.read_sql_query(text(query), engine)

In [257]:
df.head()

rating  first_year  mean_price
0     PG        2006    3.051856
1  PG-13        2006    3.034843

In [ ]:
# Where y Having hacen lo mismo pero where es antes y having es despues
# es decir where lo aplicamos al from (columnas de la tabla original)
# y having se aplica a select (columnas de la salida)
query = """SELECT rating, rental_rate AS mean_price FROM film
WHERE rental_rate > 3
HAVING mean_price > 3"""


In [ ]:
query = """SELECT rating, MIN(release_year) AS first_year, AVG(rental_rate) AS mean_price FROM film
GROUP BY rating
HAVING mean_price > 3 AND rating LIKE 'P%'"""

In [ ]:
query = """SELECT rating, MIN(release_year) AS first_year, AVG(rental_rate) AS mean_price FROM film
WHERE title LIKE 'C%'
GROUP BY rating
HAVING mean_price > 3"""

In [328]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [261]:
response = requests.get('https://es.wikipedia.org/wiki/Feminismo')

In [262]:
response

<Response [200]>

In [263]:
response.status_code # 404 no found de untener 100 200 300 400 500

200

In [265]:
type(response.content)

bytes

In [266]:
#la sopa ahora si va a ser como un html

In [267]:
soup = BeautifulSoup(response.content)

In [268]:
response.content[:1000]

b'<!DOCTYPE html>\n<html class="client-nojs" lang="es" dir="ltr">\n<head>\n<meta charset="UTF-8"/>\n<title>Feminismo - Wikipedia, la enciclopedia libre</title>\n<script>document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\\t.","\xc2\xa0\\t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],"wgRequestId":"1eb0f251-e5f5-4f7e-8a59-b1943fff8013","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Feminismo","wgTitle":"Feminismo","wgCurRevisionId":146835319,"wgRevisionId":146835319,"wgArticleId":16192,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Wikipedia:Art\xc3\xadculos con enlaces externos rotos","Wikipedia:P\xc3\xa1ginas con enlaces m\xc3\xa1gicos de ISBN","W

In [269]:
response.content[:1000]

<!DOCTYPE html>
<html class="client-nojs" dir="ltr" lang="es">
 <head>
  <meta charset="utf-8"/>
  <title>
   Feminismo - Wikipedia, la enciclopedia libre
  </title>
  <script>
   document.documentElement.className="client-js";RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":[",\t."," \t,"],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"],"wgRequestId":"1eb0f251-e5f5-4f7e-8a59-b1943fff8013","wgCSPNonce":false,"wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"Feminismo","wgTitle":"Feminismo","wgCurRevisionId":146835319,"wgRevisionId":146835319,"wgArticleId":16192,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Wikipedia:Artículos con enlaces externos rotos","Wikipedia:Páginas con enlaces mágicos de ISBN","Wikipedia:Artículos 

In [279]:
response = requests.get('https://coinmarketcap.com/')

In [280]:
response

<Response [200]>

In [281]:
soup_cryptos = BeautifulSoup(response.content)

In [282]:
print(soup_cryptos.prettify()[:1000])

<!DOCTYPE html>
<html dir="ltr" lang="en">
 <head>
  <script crossorigin="anonymous">
   (function(c,u,v,n,p,e,z,A,w){function k(a){if(!x){x=!0;var l=u.getElementsByTagName(v)[0],d=u.createElement(v);d.src=A;d.crossOrigin="anonymous";d.addEventListener("load",function(){try{c[n]=r;c[p]=t;var b=c[e],d=b.init;b.init=function(a){for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&(w[b]=a[b]);d(w)};B(a,b)}catch(g){console.error(g)}});l.parentNode.insertBefore(d,l)}}function B(a,l){try{for(var d=m.data,b=0;b<a.length;b++)if("function"===typeof a[b])a[b]();var e=!1,g=c.__SENTRY__;"undefined"!==
typeof g&&g.hub&&g.hub.getClient()&&(e=!0);g=!1;for(b=0;b<d.length;b++)if(d[b].f){g=!0;var f=d[b];!1===e&&"init"!==f.f&&l.init();e=!0;l[f.f].apply(l,f.a)}!1===e&&!1===g&&l.init();var h=c[n],k=c[p];for(b=0;b<d.length;b++)d[b].e&&h?h.apply(c,d[b].e):d[b].p&&k&&k.apply(c,[d[b].p])}catch(C){console.error(C)}}for(var f=!0,y=!1,q=0;q<document.scripts.length;q++)if(-1<document.scripts[q].src.indexOf(z)

In [ ]:
# https://super.walmart.com.mx/

In [285]:
html_ejemplo = """<!DOCTYPE html>
<html>
  <head>
      <title>Title of the document</title>
      <style>
      .info_secreta {
        border: 5px outset red;
        background-color: lightblue;
      }
      .texto_centrado {
        text-align: center;
      }
      </style>
  </head>

  <body>
    <h1> Esto es un titulon </h1>
    <a href = "https://es.wikipedia.org/wiki/Feminismo"> Esto es un link al feminismo en wikipedia </a>
    <h3> Esto es un titulin </h3>
    The content of the document......
    <p> Esto es un parrafo dentro de mi pagina </p>
    <ol>
    	<li> Primer elemento </li>
        <li> Segundo elemento </li>
        <li> Tercer elemento </li>
    </ol>

    
    <table>
    	<tr><th>Nombre</th><th>Apellido</th><th>Edad</th></tr>
        <tr><td>Zahid</td><td>Sanchez</td><td>25</td></tr>
        <tr><td>Nay</td><td>Saldivar</td><td>26</td></tr>
    </table>
    <div class = "info_secreta">
      <h2>Un titulo asi bien raro</h2>
      <p>Un parrafo un poco menos raro.</p>
    </div>
    <div class = "info_secreta texto_centrado">
      <ul>
          <li> Primer elemento </li>
          <li> Segundo elemento </li>
          <li> Tercer elemento </li>
      </ul>
    </div>
  </body>
</html> """

In [286]:
sopa_ejemplo = BeautifulSoup(html_ejemplo)

In [287]:
sopa_ejemplo.title

<title>Title of the document</title>

In [288]:
sopa_ejemplo.li

<li> Primer elemento </li>

In [289]:
sopa_ejemplo.ul

<ul>
<li> Primer elemento </li>
<li> Segundo elemento </li>
<li> Tercer elemento </li>
</ul>

In [290]:
type(sopa_ejemplo)

bs4.BeautifulSoup

In [291]:
body_ejemplo = sopa_ejemplo

In [292]:
body_ejemplo.ol


<ol>
<li> Primer elemento </li>
<li> Segundo elemento </li>
<li> Tercer elemento </li>
</ol>

In [293]:
body_ejemplo.ol.text

'\n Primer elemento \n Segundo elemento \n Tercer elemento \n'

In [294]:
print(body_ejemplo.ol.text)


 Primer elemento 
 Segundo elemento 
 Tercer elemento 



In [295]:
body_ejemplo.ol.li.text

<li> Primer elemento </li>

In [298]:
body_ejemplo.ol.li.text

' Primer elemento '

In [299]:
body_ejemplo.ol.li.string

' Primer elemento '

In [306]:
lista_lis = sopa_ejemplo.find_all('li')

In [307]:
lista_lis

[<li> Primer elemento </li>,
 <li> Segundo elemento </li>,
 <li> Tercer elemento </li>,
 <li> Primer elemento </li>,
 <li> Segundo elemento </li>,
 <li> Tercer elemento </li>]

In [308]:
sopa_ejemplo.select('table')

[<table>
 <tr><th>Nombre</th><th>Apellido</th><th>Edad</th></tr>
 <tr><td>Zahid</td><td>Sanchez</td><td>25</td></tr>
 <tr><td>Nay</td><td>Saldivar</td><td>26</td></tr>
 </table>]

In [309]:
sopa_ejemplo.a

<a href="https://es.wikipedia.org/wiki/Feminismo"> Esto es un link al feminismo en wikipedia </a>

In [312]:
sopa_ejemplo.a['href']

'https://es.wikipedia.org/wiki/Feminismo'

In [315]:
sopa_ejemplo.div['class']

['info_secreta']

In [316]:
sopa_ejemplo.find_all('div')

[<div class="info_secreta">
 <h2>Un titulo asi bien raro</h2>
 <p>Un parrafo un poco menos raro.</p>
 </div>,
 <div class="info_secreta texto_centrado">
 <ul>
 <li> Primer elemento </li>
 <li> Segundo elemento </li>
 <li> Tercer elemento </li>
 </ul>
 </div>]

In [317]:
sopa_ejemplo.find_all('div', attr = {'class':'texto_centrado'})

[]

In [318]:
sopa_ejemplo.select('div.texto_centrado')

[<div class="info_secreta texto_centrado">
 <ul>
 <li> Primer elemento </li>
 <li> Segundo elemento </li>
 <li> Tercer elemento </li>
 </ul>
 </div>]

In [319]:
sopa_ejemplo.select('a')

[<a href="https://es.wikipedia.org/wiki/Feminismo"> Esto es un link al feminismo en wikipedia </a>]

In [320]:
sopa_ejemplo.find_all('a', attrs = {'href' : 'https://es.wikipedia.org/wiki/Feminismo' })

[<a href="https://es.wikipedia.org/wiki/Feminismo"> Esto es un link al feminismo en wikipedia </a>]

In [330]:
sopa_ejemplo.select('div.info_secreta')

[<div class="info_secreta">
 <h2>Un titulo asi bien raro</h2>
 <p>Un parrafo un poco menos raro.</p>
 </div>,
 <div class="info_secreta texto_centrado">
 <ul>
 <li> Primer elemento </li>
 <li> Segundo elemento </li>
 <li> Tercer elemento </li>
 </ul>
 </div>]

In [ ]:
# https://developers.whatismybrowser.com/useragents/explore/software_name/chrome/

In [347]:
respuesta = requests.get('https://developers.whatismybrowser.com/useragents/explore/software_name/chrome/')

In [348]:
sopa_respuesta = BeautifulSoup(respuesta.content)

In [349]:
tabla_respuesta = sopa_respuesta.select('table.listing-of-useragents')[0]

In [350]:
lista_user_agents = tabla_respuesta.select('a[href]')

In [351]:
lista_user_agents[:5]

[<a class="code" href="/useragents/parse/2899915-chrome-windows-blink">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36</a>,
 <a class="code" href="/useragents/parse/1252728-chrome-windows-blink">Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36</a>,
 <a class="code" href="/useragents/parse/2441403-chrome-windows-blink">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36</a>,
 <a class="code" href="/useragents/parse/667490-chrome-windows-blink">Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36</a>,
 <a class="code" href="/useragents/parse/636-chrome-linux-blink">Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36</a>]

In [352]:
lista_user_agents[0].text

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'

In [356]:
with open('user_agents.txt', 'w') as f:
    f.writelines('\n'.join(lista_user_agents))

TypeError: sequence item 0: expected str instance, Tag found

In [354]:
def regresar_user_agents(path = 'user_agents.txt'):
    with open(path, 'r') as f:
        user_agents = f.readlines()
    return user_agents

In [359]:
import random

In [360]:
def select_user_agent(agents_list):
    return {'user_agent' : random.choice(agents_list)}

In [362]:
agents = regresar_user_agents()

In [363]:
agents = regresar_user_agents()

In [380]:
agents

[]

In [378]:
url = 'https://github.com/trending/developers'

In [381]:
response = requests.get(url)

In [385]:
response

<Response [200]>

In [386]:
sopa_git = BeautifulSoup(response.content)

In [387]:
bloques = sopa_git.select('article.Box-row.d-flex')

In [388]:
len(bloques)

25

In [389]:
bloques[0].select('div.col-md-6:first-of-type')[0]

<div class="col-md-6">
<h1 class="h3 lh-condensed">
<a data-hydro-click='{"event_type":"explore.click","payload":{"click_context":"TRENDING_DEVELOPERS_PAGE","click_target":"OWNER","click_visual_representation":"TRENDING_DEVELOPER","actor_id":null,"record_id":4660275,"originating_url":"https://github.com/trending/developers","user_id":null}}' data-hydro-click-hmac="71515a6198349161f1388602de97ec09f127095bae7bf3100180bb143d589b7d" data-view-component="true" href="/sobolevn">
            Nikita Sobolev
</a> </h1>
<p class="f4 text-normal mb-1">
<a class="Link--secondary" data-hydro-click='{"event_type":"explore.click","payload":{"click_context":"TRENDING_DEVELOPERS_PAGE","click_target":"OWNER","click_visual_representation":"TRENDING_DEVELOPER","actor_id":null,"record_id":4660275,"originating_url":"https://github.com/trending/developers","user_id":null}}' data-hydro-click-hmac="71515a6198349161f1388602de97ec09f127095bae7bf3100180bb143d589b7d" data-view-component="true" href="/sobolevn">
  

In [390]:
usuarios = [bloque.select('div.col-md-6:first-of-type')[0] for bloque in bloques ]

In [391]:
usuarios[:2]

[<div class="col-md-6">
 <h1 class="h3 lh-condensed">
 <a data-hydro-click='{"event_type":"explore.click","payload":{"click_context":"TRENDING_DEVELOPERS_PAGE","click_target":"OWNER","click_visual_representation":"TRENDING_DEVELOPER","actor_id":null,"record_id":4660275,"originating_url":"https://github.com/trending/developers","user_id":null}}' data-hydro-click-hmac="71515a6198349161f1388602de97ec09f127095bae7bf3100180bb143d589b7d" data-view-component="true" href="/sobolevn">
             Nikita Sobolev
 </a> </h1>
 <p class="f4 text-normal mb-1">
 <a class="Link--secondary" data-hydro-click='{"event_type":"explore.click","payload":{"click_context":"TRENDING_DEVELOPERS_PAGE","click_target":"OWNER","click_visual_representation":"TRENDING_DEVELOPER","actor_id":null,"record_id":4660275,"originating_url":"https://github.com/trending/developers","user_id":null}}' data-hydro-click-hmac="71515a6198349161f1388602de97ec09f127095bae7bf3100180bb143d589b7d" data-view-component="true" href="/sobole

In [394]:
usuarios[0].select('h1 a')[0].text.strip(' \n')

'Nikita Sobolev'

In [396]:
nombres = [usuario.select('h1 a')[0].text.strip(' \n') for usuario in usuarios]

In [397]:
usuarios[0].select('p a')[0].text.strip(' \n')

'sobolevn'

In [398]:
user_names = []
for usuario in usuarios:
    try:
        user_name.append()

SyntaxError: unexpected EOF while parsing (2399162618.py, line 4)

In [400]:
url2 = "https://www.nike.com/mx/w/rebajas-3yaep"

In [401]:
response = requests.get(url2)

In [402]:
response

<Response [200]>

In [403]:
sopa_git = BeautifulSoup(response.content)

In [404]:
bloques = sopa_git.select('a.product-card__link-overlay')

In [406]:
bloques[0]

<a class="product-card__link-overlay" data-testid="product-card__link-overlay" href="https://www.nike.com/mx/t/calzado-air-force-1-07-lv8-7j2wDJ/DM0118-100">Nike Air Force 1 '07 LV8</a>

In [ ]:
<a aria-label="Nike Air Force 1 '07 LV8" 

In [ ]:
bloques = sopa_git.select('a.product-card__link-overlay')

In [ ]:
#<a aria-label="Nike Air Force 1 '07 LV8" class="product-card__img-link-overlay" 

In [411]:
bloques_imagenes = sopa_git.select('a.product-card__img-link-overlay')

In [409]:
bloques[0]

<a aria-label="Nike Air Force 1 '07 LV8" class="product-card__img-link-overlay" data-el-type="Hero" data-testid="product-card__img-link-overlay" href="https://www.nike.com/mx/t/calzado-air-force-1-07-lv8-7j2wDJ/DM0118-100"><div class="wall-image-loader css-1la3v4n" data-testid="wall-image-loader"><noscript><img alt="Nike Air Force 1 '07 LV8 Calzado para hombre" class="product-card__hero-image css-1fxh5tw" height="400" loading="lazy" width="400"/></noscript></div></a>

In [412]:
bloques_imagenes[0].select('img')[0]

In [413]:
bloques_imagenes[0].select('img')[0].get('src')

'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'

In [414]:
bloques_imagenes[0].select('img')[0]['src']

'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'

In [416]:
link_imagenes = [imagen.select('img')[0]['src'] for imagen in bloques_imagenes]

In [417]:
link_imagenes

['data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
 'da

In [ ]:
<div class="product-card__info disable-animations for--product">

In [422]:
bloques_info = sopa_git.select('div.product-card__info')

In [423]:
bloques_info[0]

<div class="product-card__info disable-animations for--product"><div class=""><div class="product-card__messaging accent--color" data-testid="product-card__messaging">Lo más vendido</div><div class="product-card__titles"><div class="product-card__title" id="Nike Air Force 1 '07 LV8" role="link">Nike Air Force 1 '07 LV8</div><div class="product-card__subtitle" role="link">Calzado para hombre</div></div></div><div class="product-card__count-wrapper false false" data-testid="product-card__count-wrapper "><div class="product-card__count-item"><button aria-expanded="false" class="product-card__colorway-btn" data-testid="product-card__colorway-btn" type="button"><div aria-label="Disponible en 2 Colors" class="product-card__product-count font-override__body1">2 colores</div></button></div></div><div class="product-card__animation_wrapper"><div class="product-card__price-wrapper"><div class="product-card__price" data-testid="product-card__price" role="link"><div aria-label="precio actual $2,24

In [425]:
bloques_info[0].select('div.product-card__title')[0].text

"Nike Air Force 1 '07 LV8"

In [426]:
bloques_info[0].select('div.product-card__title')[0].get('id')

"Nike Air Force 1 '07 LV8"

In [427]:
nombres_productos = [nombre.select('div.product-card__title')[0].get('id') for nombre in bloques_info]

In [429]:
nombres_productos

["Nike Air Force 1 '07 LV8",
 'Nike Sportswear',
 'Nike Sportswear Sport Essentials+',
 'Nike Air Max Koko',
 "Nike Air Force 1 '07 LX Next Nature",
 'Jordan Chilango',
 'Air Jordan XXXVI Low Luka',
 'Nike Air Zoom SuperRep 3',
 'Nike Yoga Indy',
 'Nike Pro',
 "Nike Blazer Low '77 Jumbo",
 'Nike City Rep TR',
 'Nike Pro 365',
 'Nike Quest 5',
 'Nike Quest 5',
 'Nike Dri-FIT Academy',
 'Nike Air Max 90',
 'Nike Revolution 6 Next Nature',
 'Nike Air Force 1',
 'NikeCourt Dri-FIT Victory',
 'Jordan Sophia',
 "Nike Air Force 1 '07 ESS",
 'Nike Air Max Dawn SE',
 'Nike Sportswear']

In [477]:
descripcion_productos = [nombre.select('div.product-card__subtitle')[0].text for nombre in bloques_info]

IndexError: list index out of range

In [476]:
bloques_info = sopa_git.select('div.product-card__subtitle')

In [470]:
bloques_info[0].text

'Calzado para hombre'

In [472]:
descripcion_productos = [nombre.text for nombre in bloques_info]

In [471]:
for nombres in bloques_info:
    print(nombres.text)

Calzado para hombre
Sudadera de French Terry para hombre
Shorts Flow para hombre
Sandalias para mujer
Calzado para hombre
Sudadera con gorro sin cierre para mujer
Calzado de básquetbol para hombre
Calzado de entrenamiento para mujer
Bra deportivo sin almohadilla con gráfico de baja sujeción para mujer
Shorts de 7,5 cm para mujer
Calzado para hombre
Calzado de entrenamiento para mujer
Leggings con paneles de malla de cintura alta de 7/8 para mujer
Calzado de running en carretera para mujer
Calzado de running en carretera para hombre
Conjunto de entrenamiento de fútbol de tejido Knit para hombre
Calzado para hombre
Calzado de running en carretera para mujer
Calzado para niños grandes
Falda de tenis para mujer
Chancla para mujer
Calzado para mujer
Calzado para mujer
Sudadera con gorro sin cierre de French Terry para hombre


In [457]:
bloques_info = sopa_git.select('div.product-card__price')

In [458]:
bloques_info[0]

<div class="product-card__price" data-testid="product-card__price" role="link"><div aria-label="precio actual $2,249, precio original $2,499" class="product-price__wrapper css-1q1feg0"><div aria-hidden="true" class="product-price is--current-price css-1ydfahe" data-test="product-price-reduced" role="link">$2,249</div><div aria-hidden="true" class="product-price mx__styling is--striked-out css-0" data-test="product-price" role="link">$2,499</div></div></div>

In [461]:
bloques_info[0].select('div.product-card__price')

[]

In [466]:
bloque_precios = [nombre.text for nombre in bloques_info]

In [467]:
for nombres in bloques_info:
    print(nombres.text)

$2,249$2,499
$1,189$1,699
$799$999
$1,379$2,299
$2,024$2,699
$1,119$1,399
$2,869$4,099
$2,249$2,999
$551$849
$479$599
$1,609$2,299
$1,119$1,599
$759$949
$1,139$1,899
$1,329$1,899
$1,014$1,449
$1,959$2,799
$1,039$1,599
$1,709$1,899
$664$949
$1,399$1,999
$1,799$2,399
$1,819$2,799
$1,329$1,899


In [468]:
bloque_precios

['$2,249$2,499',
 '$1,189$1,699',
 '$799$999',
 '$1,379$2,299',
 '$2,024$2,699',
 '$1,119$1,399',
 '$2,869$4,099',
 '$2,249$2,999',
 '$551$849',
 '$479$599',
 '$1,609$2,299',
 '$1,119$1,599',
 '$759$949',
 '$1,139$1,899',
 '$1,329$1,899',
 '$1,014$1,449',
 '$1,959$2,799',
 '$1,039$1,599',
 '$1,709$1,899',
 '$664$949',
 '$1,399$1,999',
 '$1,799$2,399',
 '$1,819$2,799',
 '$1,329$1,899']

In [473]:
descripcion_productos

['Calzado para hombre',
 'Sudadera de French Terry para hombre',
 'Shorts Flow para hombre',
 'Sandalias para mujer',
 'Calzado para hombre',
 'Sudadera con gorro sin cierre para mujer',
 'Calzado de básquetbol para hombre',
 'Calzado de entrenamiento para mujer',
 'Bra deportivo sin almohadilla con gráfico de baja sujeción para mujer',
 'Shorts de 7,5 cm para mujer',
 'Calzado para hombre',
 'Calzado de entrenamiento para mujer',
 'Leggings con paneles de malla de cintura alta de 7/8 para mujer',
 'Calzado de running en carretera para mujer',
 'Calzado de running en carretera para hombre',
 'Conjunto de entrenamiento de fútbol de tejido Knit para hombre',
 'Calzado para hombre',
 'Calzado de running en carretera para mujer',
 'Calzado para niños grandes',
 'Falda de tenis para mujer',
 'Chancla para mujer',
 'Calzado para mujer',
 'Calzado para mujer',
 'Sudadera con gorro sin cierre de French Terry para hombre']

In [478]:
import bs4

In [479]:
bs4.__version__

'4.11.1'

In [480]:
nombres_productos[0]

"Nike Air Force 1 '07 LV8"

In [481]:
descripcion_productos[0]

'Calzado para hombre'

In [482]:
bloque_precios[0]

'$2,249$2,499'

In [484]:
list(zip(nombres_productos, descripcion_productos,bloque_precios))[:2]

[("Nike Air Force 1 '07 LV8", 'Calzado para hombre', '$2,249$2,499'),
 ('Nike Sportswear', 'Sudadera de French Terry para hombre', '$1,189$1,699')]

In [1]:
!pip install selenium

     ---------------------------------------- 5.2/5.2 MB 13.9 MB/s eta 0:00:00
     ------------------------------------- 384.9/384.9 kB 23.4 MB/s eta 0:00:00
     ---------------------------------------- 58.3/58.3 kB 3.2 MB/s eta 0:00:00
